"""Add fk Constraint on Users and Businesses

Revision ID: cfe0de6049c8
Revises: 10140c6257dc
Create Date: 2025-09-08 00:25:05.968963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cfe0de6049c8'
down_revision: Union[str, Sequence[str], None] = '10140c6257dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("business_owner_fk", 'businesses', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key("user_business_fk", 'users', 'businesses', ['business_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_business_fk", 'users', type_='foreignkey')
    op.drop_constraint("business_owner_fk", 'businesses', type_='foreignkey')
    # ### end Alembic commands ###
